export const ElementConfig = {
    'text':{
        type:'text',
        config:{
            styles:{
                color:'black',
                fontSize:'15px',
                fontWeight:400,
                fontStyle:'normal',
                textDecoration:'none',
                textAlign:'left'
            },
            content:'Text'
        }
    },
    'button':{
        type:'button',
        config:{
            styles:{
                container:{
                    textAlign:'center',
                },
                button:{
                    color:'white',
                    fontSize:'15px',
                    fontWeight:400,
                    padding:'9px 20px 10px',
                    fontStyle:'normal',
                    textDecoration:'none',
                    textAlign:'center',
                    backgroundColor:'#35bfbf',
                    borderColor:'black',
                    borderRadius:'4px',
                },
            },
            content:'Button'
        }
    },
    'image':{
        type:'image',
        config:{
            styles:{
                container:{
                    justifyContent:'center',
                },
                image:{
                    height:"250px",
                    width:"250px"
                },
            },
            src:'https://active-asics.de/wp-content/plugins/breedr/assets/no-image-available.png'
        }
    },
}